import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import logo from '../public/logo.svg'
import logo2 from '../public/logo2.svg'
import Image from 'next/image'
import Link from 'next/link'

const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <nav className="">
          <div className="flex h-24 items-center px-24 bg-white shadow-md">
            <Image src={logo} alt="" className="h-16 w-auto"/>
            <span className="text-blue-800 text-3xl px-4">CoffeeLife</span>
            <div className="flex space-x-8 ml-48">
              <Link className="transition delay-150 duration-300 ease-in-out hover:bg-blue-200 bg-white px-4 py-2 rounded-3xl flex" href='/'>Главная</Link>
              <Link className="transition delay-150 duration-300 ease-in-out hover:bg-blue-200 bg-white px-4 py-2 rounded-3xl flex" href='/menu'>Меню</Link>
              <Link className="transition delay-150 duration-300 ease-in-out hover:bg-blue-200 bg-white px-4 py-2 rounded-3xl flex" href='/about'>О нас</Link>
              <Link className="transition delay-150 duration-300 ease-in-out hover:bg-blue-200 bg-white px-4 py-2 rounded-3xl flex" href='/find'>Где нас найти</Link>
            </div>
          </div>
        </nav>
        {children}
        <div>
          <div className="flex h-64 px-24 items-center bg-blue-800 shadow-md">
              <Image src={logo2} alt="" className="h-16 w-auto"></Image>
              <span className="text-white text-3xl px-4">CoffeeLife</span>
              <div className="flex space-x-8 ml-48">
                <Link className="text-white transition delay-100 duration-300 ease-in-out hover:bg-blue-300 bg-blue-800 px-4 py-2 rounded-3xl flex" href='/about'>О нас</Link>
                <Link className="transition text-white delay-100 duration-300 ease-in-out hover:bg-blue-300 bg-blue-800 px-4 py-2 rounded-3xl flex" href='/menu'>Меню</Link>
                <Link className="transition delay-100 text-white duration-300 ease-in-out hover:bg-blue-300 bg-blue-800 px-4 py-2 rounded-3xl flex" href='/find'>Как нас найти</Link>
                <span className="px-4 py-2 text-white">E-mail: support@coffeelife.ru</span>
              </div>
          </div>
        </div>
      </body>
    </html>
  );
}
